### ISSUE TITLE
Watchtower DB update is not run on upgrade

### ISSUE THREAD

**Issue by chirauki** [abiquo/abiquo-cookbook#57]
Same for kinton liquibase

```
  * execute[liquibase-update] action nothing (skipped due to action :nothing)
  * execute[watchtower-liquibase-update] action nothing (skipped due to action :nothing)
```

**Comment by chirauki** [comment]
@nacx this was fixed in e5b4bbe7bad85f7cc4be44e9a3c33b7e3b486ea1 right?

**Comment by nacx** [comment]
That fixed the install recipe, but the upgrade one was already OK, so I can't tell if this is already fixed or not.

**Comment by chirauki** [comment]
I just checked this yesterday and the upgrade is actually run... Will close this one and reopen if needed.
