### ISSUE TITLE
Improve Websockify config

### ISSUE THREAD

**Issue by chirauki** [abiquo/abiquo-cookbook#59]
With recent changes to the RPM build we should provide a way to better handle the configuration of the websockify daemon.

**Comment by nacx** [comment]
Is this going to be fixed with the epic PR?

**Comment by chirauki** [comment]
I don't think so. The thing is that currently the cookbook does not configure the `/opt/websockify/abiquo.cfg` file, containing credentials for API, token expiration, etc.

**Comment by chirauki** [comment]
Included in https://github.com/abiquo/abiquo-cookbook/commit/feea49718dbf5ab493b72898eb13876aa55b5763
