### ISSUE TITLE
Cassandra does not start in CentOS 7

### ISSUE THREAD

**Issue by nacx** [abiquo/abiquo-cookbook#68]
For some reason, the Cassandra service fails to start in CentOS 7. When executed manually, apparently it starts properly. The monitoring kitchen suite fail for this reason on C7.

/cc @chirauki

**Comment by chirauki** [comment]
Maybe related to the fact that Cassandra does not provide systemd units but sysv init scripts? Same as happened with MariaDB?

**Comment by nacx** [comment]
Hmmmm not the same thing. The MariaDB process started; it was only a matter of the check. In this case, the process exits with an error status but no error log is present in the log files *sigh*
