### ISSUE TITLE
Upgrade recipe does not upgrade non-abiquo packages

### ISSUE THREAD

**Issue by chirauki** [abiquo/abiquo-cookbook#74]
In the case you have a separare DB server, running the upgrade recipe won't upgrade MariaDB, Redis or RabbitMQ packages if needed.

**Comment by nacx** [comment]
Just as a small note, it won't upgrade neither packages such as the ec2-api-tools (modified for 4.0) that are generated by us.

**Comment by nacx** [comment]
The `ext_services` profile installs RabbitMQ, MariaDB and Redis using the Chef community cookbooks. Users can configure them to install from packages, but also from sources, and customize several things that are out of the scope of this cookbook.
Given that we can't provide a consistent upgrade for all installation flavours provided in those cookbooks, we will be marking the upgrade for that profile as "out of scope" for this cookbook.
